### ISSUE TITLE
add call to action to taxonomy collections

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3383]
## Tasks
- [x] Add existing field `field_call_to_action` to the Cause, Issue, and Action Type Taxonomy vocabularies, and `drush fu dosomething_taxonomy` to export the fields into the DoSomething Taxonomy feature.
- [x] Template changes:  (`taxonomy-term.tpl.php`)
  - [x] New cta div like Static Content, where the button is hardcoded to say "Do it" and links to the Campaign Gallery on the page (e.g. `<a href="#gallery">` or whatever the div is called).  Example: http://staging.beta.dosomething.org/about
  - [x] If a value exists for `field_call_to_action`, output it above the button.
## Description

same display as static content, but should only appear on the bottom of the page above the footer

we'll want this to link to back up to the campaign tiles. I think it probably makes sense for this to take you right to the campaign tiles as opposed to the intro title, but open to what you think.

and does this then mean that we won't need the link field? if we're getting rid of that I say we get rid of the button field as well and just go with DO IT for all of these. but again let me know what you think

**Comment by aaronschachter** [comment]
The template can simply have a CTA that links up to the Campaign Gallery (no fields needed).  Is the copy the same on all of these?  If so what does it say? @mikefantini

**Comment by mikefantini** [comment]
@aaronschachter no the idea was that we wouldn't need to customize the link (cause it would just go up to the top) or the button (cause it would just say DO IT), but that one would be able to customize the copy above the button per collection.

**Comment by aaronschachter** [comment]
@deadlybutter Updated this issue with the specific tech tasks.  Wanna tackle it?

**Comment by itsjoekent** [comment]
Sure @aaronschachter

**Comment by aaronschachter** [comment]
This needs to be placed at the bottom of the template (that's why it links back up to the Gallery).

**Comment by itsjoekent** [comment]
Sorry I was looking at the page linked which had it above - I'll quickly move it
