### ISSUE TITLE
Old People

### ISSUE THREAD

**Issue by sergiitk** [DoSomethingArchive/legacy-website#4058]
### Description

AKA 26+ Club. An "old person" (26 and 26+) should:
#### User Registration
- [x] Should not be added to Mobile Commons
- [x] **Not be added** to the DoSomething Members list in MailChimp (`mailchimp_list_id` not equal to - ListID: `f2fab1dfd4` (for reference: `71893` - public facing ID)) and the **DoSomething New Members** grouping / **UserRegistration** interest group (ID# 10613)
  - [x] User **should be added** to the Old People / 26+ Club MailChimp list `mailchimp_list_id` **`a27895fe0c`** (for refernece `80825` - public facing ID) and the "General" interest_grouping -> **General Interest Group** (ID# 9613), mailchimp_group_name: **"Web Registrations"** (625)
- [x] Send a confirmation transactional email to the old person confirming they have been subscribed to the 26+ Club list. 
  - [x] Send **template name `mb-user_welcome-26plus_v1-0-0`** in message payload. https://trello.com/c/rrrHgiZC
- [ ] Adjust web page message after successful 26+ user registration from the general message "Registration successful. You are now logged in." to something supplied by @barryclark 
#### Campaign Signup
- [x] Should not be added to Mobile Commons
- [x] **Not be added** to the DoSomething Members list in MailChimp (`mailchimp_list_id` not equal to  `f2fab1dfd4` (for reference `71893` - public facing ID) and the **Campaign Specific campaign** grouping / interest group (values come from Drupal admin.
#### Mobile Commons
- [x] <del> Move Mobile Commons Signup Submissions to Message Broker</del> #3840
- [x] <del>Turn off Mobile Commons in MB payloads for persons older than 26 on registration and signups</del> #4061
#### MailChimp
- [x] Make MailChimp List IDs manageable in Drupal on "Third Party Opt-Ins" page #3841
- [x] Extend Drupal payloads with MailChimp List IDs
- [x] Replace MB MailChimp List ID setting in [`mbc-registration-email`](/DoSomething/mbc-registration-email/blob/master/MBC_UserRegistration.class.inc#L339) with the value from payload. Related issue: https://github.com/DoSomething/mbc-registration-email/issues/45
- [x] Change MailChimp List ID in Drupal payloads for 26+ Clud during registrations
- [x] Turn off MB for 26+ Club on signups
- [x] Send template name for Old People user registrations in message payload from Drupal (producer). Related: https://trello.com/c/rrrHgiZC

**Related**:
- https://github.com/DoSomething/mbc-registration-oldpeople/issues/1
- https://trello.com/c/drdgqJt9

**Comment by deezone** [comment]
@barryclark @marahml How should we manage campaign MailChimp interest group assignment for Old People? Currently DS members are put into different MailChimp interest groups for each of the staff pick campaigns. Should there be duplicates in the 26+ list interest groups?

See issue description for areas marked " **campaign specific campaign ?? -> ?? Interest Group** " for issue items that need your input.

**Comment by deezone** [comment]
@sergii-tkachenko Updated issue description with the MailChimp list and interest group IDs for the 26+ list.

**Comment by barryclark** [comment]
@DeeZone @sergii-tkachenko Dee and I chatted about this and confirmed that we should place all 26+ old people on to the Old People list only. They don't need to be added to a campaign specific group.

cc @marahml

**Comment by sergiitk** [comment]
@barryclark This means that we don't do anything on campaign signups? Just during registrations?

**Comment by deezone** [comment]
@sergii-tkachenko Correct.

**Comment by sergiitk** [comment]
Awesome. This makes the whole deal a lot easier!

**Comment by barryclark** [comment]
Just going to triple-check with @marahml in the HipChats too that she's cool with this.

**Comment by deezone** [comment]
As detailed in the issue description and repeated here for reference. The **"General"** interest_grouping (ID# 9613) should be used for MailChimp signups *_but_ an "interest group" still need to be created with an appropreate name. 

@barryclark @marahml - please create new "interest group" here vv.
- https://us4.admin.mailchimp.com/lists/dashboard/groups?id=80825 (View Groups for "General").

**Comment by barryclark** [comment]
@sergii-tkachenko, a proposed item for the checklist: After old people sign up, it'd be great if they could get a different confirmation message on site than the current one—so that we can let them know their signup is being handled differently. The current message is `Registration successful. You are now logged in.`. Is it possible to change that for old people? If so, I'll get a message put together and we can add it to the checklist. cc @DeeZone

**Comment by aaronschachter** [comment]
FYI @sergii-tkachenko @barryclark -- We are currently using String Overrides to display that "Registration successful" message instead of Drupal's default message.

**Comment by deezone** [comment]
@barryclark What's the progress on the template for the message to be sent to 26+ user registrations?

**Comment by angaither** [comment]
we love old people now.
