### ISSUE TITLE
Hot Module Launch Checklist

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4651]
These are things that need to be done before the Hot Module can be launched. These should be done throughout the next four weeks as they are unblocked by other issues being closed. Each of these changes needs to be made on **staging and prod** so that we can test everything properly.

Unblocked:
- [x] have campaign leads all set their job title in /user/edit. format should be Campaigns Manager, Health

Blocked by the decision on which 10 campaigns we're make hot for August:
- [x] goals set on custom settings for the 10 campaigns; goals should be set w/ @joshcusano and campaign leads using Josh's calculator. http://cl.ly/image/0j3p1j2d1X1j
- [x] set those 10 campaigns so that the high season date is set from August 1st 2015 to August 31st 2015. http://cl.ly/image/0J252D3g111i
- [x] make sure _no other campaigns besides these 10_ have high season date set for August 1st 2015 to August 31st 2015. can be done through sql query

Blocked by #4602:
- [x] upload photos for all campaign leads. photos an be uploaded at /user/[uid]/edit. work with @lkpttn to make sure the images that are uploaded are being output per the mock
- [x] make sure proper campaign lead is set as author for the 10 campaigns

Blocked by #4446: 
Set progress copy on https://www.dosomething.org/admin/config/dosomething/dosomething_campaign
- [x] 0-20% progress copy: Ready to rumble?! [campaign_title] starts NOW. Submit photos of the action you take and the impact you make ASAP, and then you can update as you go!
- [x] 21-40% progress copy: We’re gaining steam! Post on social to get your friends involved so we can reach [campaign_goal] [reportback_noun] [reportback_verb] -- the more the merrier, as they say!
- [x] 41-60% progress copy: Two (or three! or fifty!) [reportback_noun] [reportback_verb] are better than none. Share on social to get your friends in on the [campaign_title] action!
- [x] 61-80% progress copy: Time to kick it into high gear, comrades! Keep submitting photos of you werkin’ towards our goal of [campaign_goal] [reportback_noun] [reportback_verb]. #yourimpact
- [x] 81-99% progress copy: [campaign_goal] [reportback_noun] [reportback_verb] -- we’re comin’ atcha! Have YOU updated your photo submission lately? Keep the photos coming.
- [x] 100+% progress copy: WE MADE IT! Congrats on completely crushing our goal of [campaign_goal] [reportback_noun] [reportback_verb]. Bonus level: Let’s go above and beyond: Take MORE action! Make MORE impact! Submit MORE photos!

Blocked by #4637:
- [x] set Hot Phase Share Prompt on https://www.dosomething.org/admin/config/dosomething/dosomething_campaign to "Rally your friends to crush this goal!"

Last this to do is Enable Hot Module:
- [x] enable hot module; doesn't need to be done if #4656 is closed out
  ![image](https://cloud.githubusercontent.com/assets/6330971/8487869/d6a2b0f6-20dc-11e5-9e11-07289dfc9a32.png)

**Comment by joolaay** [comment]
@angaither Let's walk through this together on Monday as well.

**Comment by joolaay** [comment]
Arf @angaither can you show me where to add campaign lead to set the author? Is this a different field than CREATED BY?

**Comment by sbsmith86** [comment]
@julielorch you have to update the "Authoring Information" 
![screen shot 2015-07-23 at 5 16 19 pm](https://cloud.githubusercontent.com/assets/1700409/8862446/921cfe9a-315e-11e5-9c88-e4df448fd4aa.png)

**Comment by joolaay** [comment]
Thanks @sbsmith86. Can I add using Campaign lead UIDs? not everyone seems to have a handy ssmith type of handle. I'm not making sense anymore. super. <3

**Comment by sbsmith86** [comment]
@julielorch I think you have to do username

**Comment by angaither** [comment]
@julielorch and sometimes the username is set to a NUMBER. FUN... lemme know if you need halp!

**Comment by joolaay** [comment]
@angaither did we make an issue for this? "make sure no other campaigns besides these 10 have high season date set for August 1st 2015 to August 31st 2015. can be done through sql query"

**Comment by angaither** [comment]
@julielorch yep! https://github.com/DoSomething/phoenix/issues/4724
