### ISSUE TITLE
Global Deploy Checklist

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#5457]
## manual
- [x] back up the database
- [x] merge to the global branch into the dev branch (will this cause problems if we deploy before the date, probably)
- [x] update footer links in the [theme settings](https://www.dosomething.org/admin/appearance/settings/paraneue_dosomething) for global countries 
- [x] update header links in the [theme settings](https://www.dosomething.org/admin/appearance/settings/paraneue_dosomething) for global countries 
- [x] <del>run the drush commands to create translated versions of fields (@sergii-tkachenko - only for new fields)</del>
- [x] turn on modules that didn't get enabled
  - [x] pathauto i18n
  - [x] pathauto i18n node
  - [x] apachesolr_multilingual
- [x] <del>run script to make static content fields translatable</del>
- [x] delete and bulk update URL alias
- [x] re-index solr
- [x] flush all cache levels (fastly, varnish, drupal)
- [ ]  import PO files for each supported language
- [ ] Create Redirect from /mx/campaigns to /mx/campanas (tilda)
## double check these things
- [ ] check to make sure on /edit of campaigns that redirects are in place for all languages
- [x] make sure we have translated nodes
- [x] create translated versions of the homepage
- [x] update the site language default to en-global
- [x] break out translated nodes to be translated homepage, static content, campaigns
- [x] Confirm all four home pages w/correct URLs
- [ ] Confirm images load on all four home pages
- [x] Confirm that default language is Global English
- [x] Confirm header links correctly prepend different country prefixes
- [x] Tag global -> dev merge commit as new minor release (2.0)
- [ ] Determine & test behavior when deployed to freestanding affiliate sites
- [ ] check that global campaigns with US-scholarshipped companions don't show scholarship language on pitch or action page
- [x] check that now all links/redirects previously going to dosomething.org/something are now going to dosomething.org/us/something
- [ ] set default translated aliases for /campaigns (i.e. /voluntario) and /about
- [x] tell staff members to clear cache on browsers

**Comment by mikefantini** [comment]
- [ ] break out translated nodes to be translated homepage, static content, campaigns

**Comment by mshmsh5000** [comment]
- [ ] Confirm all four home pages w/correct URLs
- [ ] Confirm images load on all four home pages
- [ ] Confirm Node i18n pathauto is on
- [ ] Confirm that default language is Global English

**Comment by weerd** [comment]
- [ ] Enable POTx Module for Drupal
- [ ] Enable POEditor Module for Drupal

**Comment by mikefantini** [comment]
next week we'll decide when we will do a test run of this on staging with the production db

**Comment by mshmsh5000** [comment]
- [ ] Confirm header links correctly prepend different country prefixes

**Comment by mshmsh5000** [comment]
- [ ] Tag global -> dev merge commit as new minor release (1.4.0)

**Comment by mshmsh5000** [comment]
- [ ] Determine & test behavior when deployed to freestanding affiliate sites

**Comment by namimody** [comment]
- [ ] check that global campaigns with US-scholarshipped companions don't show scholarship language on pitch or action page

**Comment by namimody** [comment]
- [ ] check that now all links/redirects previously going to dosomething.org/something are now going to dosomething.org/us/something

**Comment by mikefantini** [comment]
- [ ] set default translated aliases for /campaigns (i.e. /voluntario) and /about

**Comment by angaither** [comment]
hey, we did this.

**Comment by weerd** [comment]
Should we create a new issue for when activating full translations on Prod? Cause importing POT files is still a thing that would need to get checked off :)

**Comment by angaither** [comment]
@weerd if you'd like to, though it's not really a code change, up to you!

**Comment by weerd** [comment]
K, probs not a big deal to have to remember it. Just wasn't sure if there were other things as well, and the POT one could be lumped in. No worries ;)
