### ISSUE TITLE
Transactional Payload checklist

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#5470]
**Related issues**: 
- Global Campaign Report backs bug: https://github.com/DoSomething/phoenix/issues/5487
- Global Campaign Signup bug: https://github.com/DoSomething/phoenix/issues/5486
- Global User registration and Password Reset pending deployment to Thor.

| Message Type | Global (non-affiliate country) | United States (US) | Brazil (BR) | Mexico (MX) |
| :-- | :-: | :-: | :-: | :-: |
| User Registration | [x] | [x] | [x] | [x] |
| User Password Reset | [x] | [x] | [x] | [x] |
| Campaign Signup | [x] | [x] | [x] | [x] |
| Campaign Reportback | [x] | [x] | [x] | [x] |

**Comment by DeeZone** [comment]
Fixes #5418

Bug fix to ensure settings for `user_country` and `user_language` in `dosomething_mbp()` params.

**To test**:
- Review payload produced in request to RabbitMQ / Message Broker `loggingQueue` (/queues/dosomething/loggingQueue). It should look like:

- **user_register**:
```
Array
(
    [activity] => user_register
    [email] => ascottdicker+BrazilThor@dosomething.org
    [uid] => 3118629
    [user_language] => pt-br
    [user_country] => BR
    [merge_vars] => Array
        (
            [MEMBER_COUNT] => 4.2 million
            [FNAME] => Ariél
        )
    [email_template] => mb-user-register-BR
    [mailchimp_list_id] => 66fd18c5a9
    [birthdate] => 631152000
    [subscribed] => 1
    [email_tags] => Array
        (
            [0] => drupal_user_register
        )
    [activity_timestamp] => 1444413729
    [application_id] => US
)
```
- **user_password**
```
Array
(
    [activity] => user_password
    [email] => ascottdicker+BrazilThor@dosomething.org
    [uid] => 3118629
    [user_language] => pt-br
    [user_country] => BR
    [merge_vars] => Array
        (
            [MEMBER_COUNT] => 4.2 million
            [FNAME] => Ariél
            [RESET_LINK] => https://thor.dosomething.org/br/user/reset/3118629/1444415436/GCfGZZ5_ph42o-d-v4NlPASoIfvvunjzIKEr9kfcnRk
        )

    [email_template] => mb-user-password-BR
    [email_tags] => Array
        (
            [0] => drupal_user_password
        )
    [activity_timestamp] => 1444415436
    [application_id] => US
)
```

**Comment by deezone** [comment]
**Test `user_register`**:
- [x] `user_language` = `en`
- [x] `user_country` = `US`
- [x] `email_template` = `mb-user-register-US`
- [x] `mailchimp_list_id` = `f2fab1dfd4` (General US DoSomething list)

```
Array
(
    [activity] => user_register
    [email] => dlee+thorUS01@dosomething.org
    [uid] => 3118613
    [user_language] => en
    [user_country] => US
    [merge_vars] => Array
        (
            [MEMBER_COUNT] => 4.2 million
            [FNAME] => Dee Thor Us 1
        )
    [email_template] => mb-user-register-US
    [mailchimp_list_id] => f2fab1dfd4
    [birthdate] => 929232000
    [subscribed] => 1
    [email_tags] => Array
        (
            [0] => drupal_user_register
        )

    [activity_timestamp] => 1444339916
    [application_id] => US
)
```

**Comment by deezone** [comment]
**Test `user_password`**:
- [x] `user_language` = `en`
- [x] `user_country` = `US`
- [x] `[merge_vars][RESET_LINK]` has country subdomain `\us\`
- [x] `email_template` = `mb-user-password-US`

```
Array
(
    [activity] => user_password
    [email] => dlee+thorUS01@dosomething.org
    [uid] => 3118613
    [user_language] => en
    [user_country] => US
    [merge_vars] => Array
        (
            [MEMBER_COUNT] => 4.2 million
            [FNAME] => Dee Thor Us 1
            [RESET_LINK] => https://thor.dosomething.org/us/user/reset/3118613/1444341234/kHmXkHV0upL-wbO-KqkGvmnpOnSNc67Ewm7knc6LAqA
        )
    [email_template] => mb-user-password-US
    [email_tags] => Array
        (
            [0] => drupal_user_password
        )
    [activity_timestamp] => 1444341234
    [application_id] => US
)
```

**Comment by mikefantini** [comment]
@DeeZone what's blocking this?

**Comment by deezone** [comment]
@mikefantini Review items further, two new items blocking this review issue. See links to issues in description above.

**Comment by deezone** [comment]
All transactions produce expected results in the country / language for each of the four (US, Global, MX, BR) options.
