### ISSUE TITLE
Google Analytics - Tracking Additional Onboarding Screens 

### ISSUE THREAD

**Issue by jessleenyc** [DoSomethingArchive/legacy-website#6756]
#### User Story

As an admin, I want to track which screens are visited and which screens people are closing out of during onboarding. 
#### Additional Info
- 3 events to count each onboarding screen
- 3 events to track the 'X' button on each screen
#### Why This Matters

This will help us determine the success of the onboarding feature.

**Comment by itsjoekent** [comment]
for now ill just make an event trigger if the onboarding flow is displayed

**Comment by itsjoekent** [comment]
## PR 1
- [x] Log every time a user reaches a new slide (Log slide name In the label? Or event per slide type?)
- [x] Log every time someone clicks the Next & Prev buttons
- [x] Log every time someone clicks the close button (Log slide name in the label)

## PR 2
- [ ] Log time spent interacting with onboarding. (Not sure what the best approach is, need to somehow check if onboarding is visible to the user.)
- [ ] Log time spent between view more clicks. Are people just spamming this or are they reading the card?
