### ISSUE TITLE
Running List of Possible Next Steps for /magicks Links

### ISSUE THREAD

**Issue by ngjo** [DoSomethingArchive/legacy-website#7025]
For the sake of consolidating, here are some possible next steps. We should create issues for them once we decide which one's we want to work on so that we can track progress through the issues vs having this one open for a while. 

Just because it's listed here doesn't mean we're doing it! In no particular order (we can discuss) 
- [x] Adding redirect option to take the user to the campaign page -- ISSUE CREATED #7027 
- [x] Trigger transactional email ("thanks for signing up") when member clicks sign-up -- note for diego: "I believe I’m passing false to indicate to not send" -- ISSUE CREATED #7028 
- [x] login modal vs show action page and restrict the RB uploading -- ISSUE CREATED #7029 
- [x] Key token to stop spammers -- ISSUE CREATED #7030 
- [ ] Consider filling in the user's email address in the login modal
- [x] Talking about the mobile user experience (will it open a mobile browser).
  ----- We discussed this and the experience isn't that foreign so shouldn't be an issue. The tech will work the same (user clicks SIGN UP in mobile and mobile browser opens, they're signed up)
- [ ] Other uses (scholarship page, campaigns page, SMS...throwing things out there!)
- [ ] Testing all of this in the wilddddd
- [x] Not sure if this just a GA thing, but would like to talk about some sort of tracking system to see how many people are clicking and then signing up (possibly RB too? not sure if this is too lofty). Basically, wanna be able to measure the success/impact of this
  ----- add a &source= to the URL and it'll be tracked in the sign-up table. This does not tie to RBs

@weerd Plz add if I missed anything!

**Comment by weerd** [comment]
👍
