### ISSUE TITLE
[Feature] Affiliate Messaging Opt-ins

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#7296]
_FEATURE OVERVIEW_
-------------------
#### User Story
As a user I would like to be able to opt-in (out) to receive email messaging from DoSomething affiliates when I sign up for a campaign, regardless of whether I'm signed in.

#### Additional Information (optional)
Add a toggle and label underneath the campaign signup button on the pitch page (for both unauthenticated and authenticated users) to allow them to decide whether they want messaging from affiliates or not. Also allow campaign leads to add more information for the user, as well as an ability to export from the database a CSV list of users that _did_ sign up.

#### Why This Matters
We want to give our affiliates an opportunity to contact users that have signed up for a campaign they are specifically sponsoring or are a partner with.

#### Tasks
This feature includes the following tasks:
- [x] add form for specifying affiliate information on a per campaign basis [#7286](https://github.com/DoSomething/phoenix/pull/7286)
- [x] update the pitch page to output the opt-in data [#7286](https://github.com/DoSomething/phoenix/pull/7286)
- [x] style the pitch page opt-in data
- [x] save record of users that opt-in(out) to affiliate messaging per campaign [#7292](https://github.com/DoSomething/phoenix/pull/7292)
- [x] add export form and allow it to export CSV of opt-in users for a campaign [#7306](https://github.com/DoSomething/phoenix/pull/7306)
- [x] enable affiliate opt-in(out) on pitch page for authenticated users [#7292](https://github.com/DoSomething/phoenix/pull/7292)
- [x] enable affiliate opt-in(out) on pitch page for unauthenticated users [#7301](https://github.com/DoSomething/phoenix/pull/7301)
- [x] Fix styling of message callout when opt-in/out is present

#### Checklist
- [x] Tested on staging.
- [x] Pinged a PM if this is a larger PR that would benefit from some additional testing love
- [x] Post a message in #phoenix if this includes something that causes a rebuild!

**Comment by ngjo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(5) As a biz dev, I want to build an Opt-out Option for 3rd party messaging during sign up.](https://trello.com/c/YmS6rixd/216-5-as-a-biz-dev-i-want-to-build-an-opt-out-option-for-3rd-party-messaging-during-sign-up)
