### ISSUE TITLE
system message styles

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#971]
Need to update the notification for when a user signs up for a campaign and when a user returns to a campaign they are already signed up for.

Notification messages should look like this:
https://s3.amazonaws.com/uploads.hipchat.com/34218/407723/jn8yiKwQ2EQROAt/Action%20Page%20Notification.pdf

**Comment by mmwtsn** [comment]
**TODO**
- [x] update template file (paraneue)
- [x] update base message styles (neue)
- [x] create ~~modal~~ message JS function (neue)

**Comment by aaronschachter** [comment]
Hey @mmwtsn -- looking at the messages with @mikefantini. He requesting to display the messages `<ul>` as inline, so they don't appear with separate line breaks.

![screen shot 2014-03-13 at 12 56 17 pm](https://f.cloud.github.com/assets/1236811/2412264/8ce13970-aad0-11e3-9687-5f0229c2811a.png)

**Comment by mikefantini** [comment]
oh sorry I misunderstood. I'm open to whether we want to do inline or stacked (whatever you think is best @mmwtsn). I just wanted to make sure that it would be just one notification message so that the user could just close out one message rather than having to close out multiples.

**Comment by barryclark** [comment]
@mmwtsn Not sure this needs to be a modal? Looks like it displays above the site header and pushes everything else down? (cc @mikefantini)

**Comment by mikefantini** [comment]
yeah that is the desired layout. 

in terms of functionality the user should be able to interact with the page even if they don't close out of the notification.
